### ISSUE TITLE
License interaction is unclear

### ISSUE THREAD

**Issue by vi** [EvgenijM86/emercoin#2]
> Emercoin is released under the terms of the MIT license AND GPL3 license. See COPYING for more information or see http://www.gnu.org/licenses/gpl.html.

Is it dual licensing or something else? Either way the term "dual licensing" should be mentioned (e.g. "this is not a dual licensing" or "the code is dual licensed under GPLv3 and MIT").

`COPYING`:
> (text of MIT)
> Sublicense of Emercoin is GPL3:
> (text of GPL)

What does "sublicense" mean here?

**Comment by EvgenijM86** [comment]
I used that term because it was mentioned in MIT license.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, <b>sublicense</b>

Basically it is GPL3 with MIT header attached, because MIT requires it to be attached.
